several package manager improvements

diff --git a/addon_files/redmatic/bin/redmatic-pkg b/addon_files/redmatic/bin/redmatic-pkg
--- a/addon_files/redmatic/bin/redmatic-pkg
+++ b/addon_files/redmatic/bin/redmatic-pkg
@@ -17,6 +17,12 @@ function usage()
     echo ""
 }
 
+function error()
+{
+    echo "Error: $1"
+    exit 1
+}
+
 function install()
 {
     PACKAGE="$1"
@@ -25,8 +31,8 @@ function install()
     VERSION=`jq -r ".\"$PACKAGE\".version" $REPO`
 
     if [ $URL == "null" ]; then
-      echo "unknown package: $1"
-      exit 1
+        echo "Error: unknown package: $1"
+        exit 1
     fi
 
     if [ -f $ADDON_DIR/lib/node_modules/$PACKAGE/package.json ]; then
@@ -42,24 +48,25 @@ function install()
     echo "Get $URL"
     set -o pipefail
     T_START=$(date +"%s")
-    /usr/bin/curl $URL -o $ADDON_DIR/tmp/$1.tar.gz --fail --show-error --silent --location || exit 1
+    /usr/bin/curl $URL -o $ADDON_DIR/tmp/$1.tar.gz --fail --show-error --silent --location 2>&1 || error "Install failed."
     T_END=$(date +"%s")
     echo "Downloaded $(stat -c %s $ADDON_DIR/tmp/$1.tar.gz | awk '{ suffix="KMGT"; for(i=0; $1>1024 && i < length(suffix); i++) $1/=1024; print int($1) substr(suffix, i, 1), $3; }')in $(( T_END-T_START )) seconds"
 
     D_INTEGRITY=sha512-$(cat $ADDON_DIR/tmp/$1.tar.gz | /usr/bin/openssl sha512 -binary | base64 | tr -d \\n)
-
     if [ "$INTEGRITY" == "$D_INTEGRITY" ]; then
         echo "File integrity check successful"
     else
         echo "File integrity check failed"
+        echo "  Expected $INTEGRITY"
+        echo "  Got      $D_INTEGRITY"
         rm $ADDON_DIR/tmp/$1.tar.gz
-        exit 1
+        error "Install failed."
     fi
 
     rm -r $ADDON_DIR/lib/node_modules/$PACKAGE 2> /dev/null
 
     echo "Extracting $1.tar.gz"
-    (cd $ADDON_DIR ; tar --no-same-owner -xzf tmp/$1.tar.gz) || exit 1
+    (cd $ADDON_DIR ; tar --no-same-owner -xzf tmp/$1.tar.gz) || error "Install failed."
 
     rm $ADDON_DIR/tmp/$1.tar.gz
     echo "Done."
