limit maximum download time to 720sec (results in min ~220kbit/s to download a 20MB file) (Mitigate #267)

diff --git a/addon_files/redmatic/bin/redmatic-pkg b/addon_files/redmatic/bin/redmatic-pkg
--- a/addon_files/redmatic/bin/redmatic-pkg
+++ b/addon_files/redmatic/bin/redmatic-pkg
@@ -48,7 +48,7 @@ function install()
     echo "Get $URL"
     set -o pipefail
     T_START=$(date +"%s")
-    /usr/bin/curl $URL -o $ADDON_DIR/tmp/$1.tar.gz --fail --show-error --silent --location 2>&1 || error "Install failed."
+    /usr/bin/curl $URL -o $ADDON_DIR/tmp/$1.tar.gz --fail --show-error --silent --max-time 720 --location 2>&1 || error "Download failed."
     T_END=$(date +"%s")
     echo "Downloaded $(stat -c %s $ADDON_DIR/tmp/$1.tar.gz | awk '{ suffix="KMGT"; for(i=0; $1>1024 && i < length(suffix); i++) $1/=1024; print int($1) substr(suffix, i, 1), $3; }')in $(( T_END-T_START )) seconds"
 
